export const GET_SPORT_DATA = "GET_SPORT_DATA";
export const SET_POPULAR_LEAGUES_DATA = "SET_POPULAR_LEAGUES_DATA";
export const SET_CURRENT_PAGE_SPORT_TYPE_DATA =
    "SET_CURRENT_PAGE_SPORT_TYPE_DATA ";
export const SET_CURRENT_PAGE_SPORT_LEAGUES_DATA =
    "SET_CURRENT_PAGE_SPORT_LEAGUES_DATA";
export const SET_CURRENT_PAGE_SPORT_EVENT_DATA =
    "SET_CURRENT_PAGE_SPORT_EVENT_DATA";

export const PUSH_ADDITIONAL_LEAGUE_ITEM = "PUSH_ADDITIONAL_LEAGUE_ITEM";
export const REMOVE_ADDITIONAL_LEAGUE_ITEM = "REMOVE_ADDITIONAL_LEAGUE_ITEM";
export const PUSH_ADDITIONAL_SPORT_TYPE_ITEM =
    "PUSH_ADDITIONAL_SPORT_TYPE_ITEM";
export const REMOVE_ADDITIONAL_SPORT_TYPE_ITEM =
    "REMOVE_ADDITIONAL_SPORT_TYPE_ITEM";
export const DELETE_API_MATCHES = "DELETE_API_MATCHES";

export const ACTIVATE_BETSLIP = "ACTIVATE_BETSLIP";
export const ADD_MATCH_TO_BETSLIP = "ADD_MATCH_TO_BETSLIP";
export const DELETE_MATCH_FROM_BETSLIP = "DELETE_MATCH_FROM_BETSLIP";
export const CALCULATE_FINAL_STAKE_AMOUNT = "CALCULATE_FINAL_STAKE_AMOUNT";
export const SET_ZERO__FINAL_STAKE_AMOUNT = "SET_ZERO__FINAL_STAKE_AMOUNT";
export const GET_PERFORMED_STAKES = "GET_PERFORMED_STAKES";
export const BETSLIP_ERROR = "BETSLIP_ERROR";
// export const SET_CURRENT = 'SET_CURRENT';
// export const CLEAR_CURRENT = 'CLEAR_CURRENT';
// export const UPDATE_CONTACT = 'UPDATE_CONTACT';
// export const FILTER_CONTACTS = 'FILTER_CONTACTS';
// export const CLEAR_CONTACTS = 'CLEAR_CONTACTS';
// export const CLEAR_FILTER = 'CLEAR_FILTER';
// export const CONTACT_ERROR = 'CONTACT_ERROR';
export const SET_ALERT = "SET_ALERT";
export const SET_ALERTS = "SET_ALERTS";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
